# Generated by Django 4.2.4 on 2023-09-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://th.bing.com/th/id/OIP.kz5A86qjMCk6lHYchAsRZAHaHa?pid=ImgDet&rs=1', max_length=600),
        ),
    ]
