# Generated by Django 4.2.6 on 2023-10-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://th.bing.com/th/id/OIP.kz5A86qjMCk6lHYchAsRZAHaHa?pid=ImgDet&rs=1', max_length=500),
        ),
    ]
